// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceStore.Models;

namespace ServiceStore.Migrations
{
    [DbContext(typeof(ServiceStoreContext))]
    partial class ServiceStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ServiceStore.Models.ServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AllowAttachments");

                    b.Property<string>("Description");

                    b.Property<int?>("ServiceTeamId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTeamId");

                    b.ToTable("ServiceItems");
                });

            modelBuilder.Entity("ServiceStore.Models.ServiceTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ServiceTeam");
                });

            modelBuilder.Entity("ServiceStore.Models.ServiceItem", b =>
                {
                    b.HasOne("ServiceStore.Models.ServiceTeam")
                        .WithMany("ServiceItems")
                        .HasForeignKey("ServiceTeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
